//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardStock
    {
        public string reg_date { get; set; }
        public string reg_time { get; set; }
        public string serial_no { get; set; }
        public string status { get; set; }
        public string reg_id { get; set; }
        public string first_sn { get; set; }
        public string last_sn { get; set; }
        public string custdist_date { get; set; }
        public string custdist_time { get; set; }
        public string custdist_id { get; set; }
        public string custIDNo { get; set; }
        public string damage_date { get; set; }
        public string damage_time { get; set; }
        public string damage_id { get; set; }
        public string remarks { get; set; }
    
        public virtual CIF CIF { get; set; }
    }
}
