//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HIJREntities : DbContext
    {
        public HIJREntities()
            : base("name=HIJREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardStock> CardStocks { get; set; }
        public virtual DbSet<CIF> CIFs { get; set; }
        public virtual DbSet<DokumenRujukan> DokumenRujukans { get; set; }
        public virtual DbSet<DokumenTravel> DokumenTravels { get; set; }
        public virtual DbSet<Kesihatan> Kesihatans { get; set; }
        public virtual DbSet<Pergerakan> Pergerakans { get; set; }
        public virtual DbSet<RefBagasi> RefBagasis { get; set; }
        public virtual DbSet<RefNegeri> RefNegeris { get; set; }
        public virtual DbSet<Penempatan> Penempatans { get; set; }
        public virtual DbSet<RefKursusPerdana> RefKursusPerdanas { get; set; }
    }
}
