//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penempatan
    {
        public string NoIC { get; set; }
        public string NoAkaun { get; set; }
        public string NoKT { get; set; }
        public string NoKumpulan { get; set; }
        public string NoMaktab { get; set; }
        public Nullable<int> NoKursus { get; set; }
        public string NoHotel1 { get; set; }
        public string NoBilik1 { get; set; }
        public string NoHotel2 { get; set; }
        public string NoBilik2 { get; set; }
    
        public virtual CIF CIF { get; set; }
        public virtual RefKursusPerdana RefKursusPerdana { get; set; }
    }
}
