//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pergerakan
    {
        public string NoIC { get; set; }
        public string Sah { get; set; }
        public string Kursus { get; set; }
        public string Kesihatan { get; set; }
        public string TPassJH { get; set; }
        public string SPassJH { get; set; }
        public string Bagasi { get; set; }
        public string KelanaJaya { get; set; }
        public string HotelMekah { get; set; }
        public string HotelMadinah { get; set; }
    
        public virtual CIF CIF { get; set; }
    }
}
