//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefKursusPerdana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefKursusPerdana()
        {
            this.Penempatans = new HashSet<Penempatan>();
        }
    
        public int NoKursus { get; set; }
        public string KodNegeri { get; set; }
        public string Lokasi { get; set; }
        public string Tarikh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penempatan> Penempatans { get; set; }
        public virtual RefNegeri RefNegeri { get; set; }
    }
}
