//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijrDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefNegeri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefNegeri()
        {
            this.CIFs = new HashSet<CIF>();
            this.RefKursusPerdanas = new HashSet<RefKursusPerdana>();
        }
    
        public string KodNegeri { get; set; }
        public string Negeri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIF> CIFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefKursusPerdana> RefKursusPerdanas { get; set; }
    }
}
